### ISSUE TITLE
限制原始碼的版本（tag）

### ISSUE THREAD

**Issue by MilesChou** [ganhuaruanti/laravel-source-study#1]
程式多少都會更新，如果沒有限制版本（tag）的話，未來可能會找不到原始碼在哪裡。

程式更新後，用註解的方法補充即可。

另外程式更新的過程也可以看出許多有趣的設計概念。

**Comment by flamerecca** [comment]
定版還真是件很麻煩的事⋯⋯找時間補上

**Comment by flamerecca** [comment]
https://github.com/ganhuaruanti/laravel-source-study/blob/master/install.md

目前改成這樣
